vtk_module(vtkFiltersFlowPaths
  GROUPS
    StandAlone
  KIT
    vtkParallel
  TEST_DEPENDS
    vtkFiltersAMR
    vtkFiltersImaging
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionStyle
    vtkRenderingOpenGL2
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkCommonMath
  PRIVATE_DEPENDS
    vtkFiltersCore
    vtkFiltersGeometry
    vtkFiltersSources
    vtkIOCore
  )
