vtk_module(vtkPVClientServerCoreRendering
  GROUPS
    ParaViewRendering
  DEPENDS
    vtkPVClientServerCoreCore
    vtkCommonDataModel
    vtkIOLegacy
    vtkPVVTKExtensionsCore
  TEST_LABELS
    PARAVIEW
  KIT
    vtkPVClientServer
)
